%******************************************************************************
% Padenti Library
%
% Copyright (C) 2015  Daniele Pianu <daniele.pianu@ieiit.cnr.it>
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Lesser General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>
%******************************************************************************/
 
function [] = build_padenti_wrappers()
%BUILD_WRAPPER Building function for the Padenti library Matlab wrapper

  mex CFLAGS='$CFLAGS -fopenmp -march=native' ...
      -DBOOST_ALL_DYN_LINK ...
      -I/home/daniele/ieiit/tools/boost/boost_1_49_0 ...
      -I/usr/local/include/padenti/ ...
      -L/usr/local/MATLAB/MATLAB_Production_Server/R2015a/bin/glnxa64/ ...
      -lboost_chrono -lboost_system ...
      -lrt -lpthread -lOpenCL...
      padenti_train.cpp

  mex CFLAGS='$CFLAGS -fopenmp -march=native' ...
      -DBOOST_ALL_DYN_LINK ...
      -I/home/daniele/ieiit/tools/boost/boost_1_49_0 ...
      -I/usr/local/include/padenti/ ...
      -L/usr/local/MATLAB/MATLAB_Production_Server/R2015a/bin/glnxa64/ ...
      -lboost_chrono -lboost_system ...
      -lrt -lpthread -lOpenCL...
      padenti_init.cpp
  
  mex CFLAGS='$CFLAGS -fopenmp -march=native' ...
      -DBOOST_ALL_DYN_LINK ...
      -I/home/daniele/ieiit/tools/boost/boost_1_49_0 ...
      -I/usr/local/include/padenti/ ...
      -L/usr/local/MATLAB/MATLAB_Production_Server/R2015a/bin/glnxa64/ ...
      -lboost_chrono -lboost_system ...
      -lrt -lpthread -lOpenCL...
      padenti_clear.cpp
  
  mex CFLAGS='$CFLAGS -fopenmp -march=native -O3' ...
      -DBOOST_ALL_DYN_LINK ...
      -I/home/daniele/ieiit/tools/boost/boost_1_49_0 ...
      -I/usr/local/include/padenti/ ...
      -L/usr/local/MATLAB/MATLAB_Production_Server/R2015a/bin/glnxa64/ ...
      -lboost_chrono -lboost_system ...
      -lrt -lpthread -lOpenCL...
      padenti_predict.cpp
  
end
